### PR TITLE
Add PersistentSet and PersistentFrozenSet to pmemobj

### PR DESCRIPTION
**Pull request by catalin-manciu**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pynvm/19)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[nvm/pmemobj/set.py, line 43 at r4](https://reviewable.io:443/reviews/pmem/pynvm/19#-Ksmo5jPQeEXwMGk2Ifq:-Ksmo5jPQeEXwMGk2Ifr:b4cblcm) ([raw file](https://github.com/pmem/pynvm/blob/8a44499cebd3ce23335a931a83db569aeb417232/nvm/pmemobj/set.py#L43)):*
> ```Python
>                               type_num=SET_POBJPTR_ARRAY_TYPE_NUM)
>             table_data = ffi.cast('PSetEntry *', mm.direct(table))
>             for i in range(tablesize):
> ```

As I can see, mm.malloc() implementation is based on pmemobj_tx_zalloc, so the memory is zeroed. There's no need to fill the table with NULL-oids, unused hashes.

BTW, I think it would be better to have both mm.malloc() and mm.zalloc().

---

*[nvm/pmemobj/set.py, line 101 at r4](https://reviewable.io:443/reviews/pmem/pynvm/19#-Ksmm5QUoBiUMjOgqWW0:-Ksmm5QUoBiUMjOgqWW1:b-7aa1rx) ([raw file](https://github.com/pmem/pynvm/blob/8a44499cebd3ce23335a931a83db569aeb417232/nvm/pmemobj/set.py#L101)):*
> ```Python
>         mm = self._p_mm
> 
>         if minused > 50000:
> ```

Since each reallocation is costly (much more than for DRAM), for PERM_SET_MINSIZE (8) I'd jump to directly to 64.

---

*[nvm/pmemobj/set.py, line 450 at r4](https://reviewable.io:443/reviews/pmem/pynvm/19#-Ksn9vU7Trqgc8a6CTRE:-Ksn9vU7Trqgc8a6CTRF:ba4qvr2) ([raw file](https://github.com/pmem/pynvm/blob/8a44499cebd3ce23335a931a83db569aeb417232/nvm/pmemobj/set.py#L450)):*
> ```Python
>                 mm.decref(table_data[keyindex].key)
>                 table_data[keyindex].key = mm.OID_NULL
>                 table_data[keyindex].hash = HASH_DUMMY
> ```

why not HASH_UNUSED? what's the reason for using these two values?

---

*[tests/test_pmemobj_set.py, line 347 at r4](https://reviewable.io:443/reviews/pmem/pynvm/19#-KsnAsasQSW8Tj_T7cZk:-KsnAsasQSW8Tj_T7cZl:b-39djoo) ([raw file](https://github.com/pmem/pynvm/blob/8a44499cebd3ce23335a931a83db569aeb417232/tests/test_pmemobj_set.py#L347)):*
> ```Python
>     thetype = pmemobj.PersistentFrozenSet
>     basetype = thetype
> ```

no tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pynvm/19)*

**Comment by catalin-manciu** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[nvm/pmemobj/set.py, line 450 at r4](https://reviewable.io:443/reviews/pmem/pynvm/19#-Ksn9vU7Trqgc8a6CTRE:-KtTcl30jTzbXa69WZrV:b-rpydqc) ([raw file](https://github.com/pmem/pynvm/blob/8a44499cebd3ce23335a931a83db569aeb417232/nvm/pmemobj/set.py#L450)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

why not HASH_UNUSED? what's the reason for using these two values?
</blockquote></details>

The UNUSED/DUMMY slot types come into play in case of a hash collision, for example:
- Given a set, we insert the keys a and b which have colliding hashes (hash(a) == hash(b)).
- First we insert a, and its index 'i' in the table_data array will be determined by some bits of its hash.
- Then we try to insert b, but since its hash is the same as a's, the same index 'i' will result out of it, and since that slot is already taken by a, we find it another empty slot using the search algorithm in the loop -> j
- Now we delete a - which means marking the entry at index 'i' as not in use, b is still at index j.
- If after we have deleted a, we try to check if b is in the set -> we will get its hash, and, since it collides with a's, the index 'i' will result.
- If at index 'i' we have an entry marked as UNUSED, we will falsely assume 'b' isn't in the set. But if we mark it differently, with 'DUMMY', we know that there was an entry there and new entries might have collided with it and have been moved to another index, so we continue searching until we get to index 'j' and find b. 

---

*[tests/test_pmemobj_set.py, line 347 at r4](https://reviewable.io:443/reviews/pmem/pynvm/19#-KsnAsasQSW8Tj_T7cZk:-KtThqe6xwscu1kc34U2:b-7j7ezk) ([raw file](https://github.com/pmem/pynvm/blob/8a44499cebd3ce23335a931a83db569aeb417232/tests/test_pmemobj_set.py#L347)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

no tests?
</blockquote></details>

The TestPersistentFrozenSet class inherits from JointOps, so all the tests from the JointOps class are ran for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pynvm/19)*

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[nvm/pmemobj/set.py, line 450 at r4](https://reviewable.io:443/reviews/pmem/pynvm/19#-Ksn9vU7Trqgc8a6CTRE:-KtVBnIHR8QYUsILTS95:blvxvet) ([raw file](https://github.com/pmem/pynvm/blob/8a44499cebd3ce23335a931a83db569aeb417232/nvm/pmemobj/set.py#L450)):*
<details><summary><i>Previously, catalin-manciu (Catalin G. Manciu) wrote…</i></summary><blockquote>

The UNUSED/DUMMY slot types come into play in case of a hash collision, for example:
- Given a set, we insert the keys a and b which have colliding hashes (hash(a) == hash(b)).
- First we insert a, and its index 'i' in the table_data array will be determined by some bits of its hash.
- Then we try to insert b, but since its hash is the same as a's, the same index 'i' will result out of it, and since that slot is already taken by a, we find it another empty slot using the search algorithm in the loop -> j
- Now we delete a - which means marking the entry at index 'i' as not in use, b is still at index j.
- If after we have deleted a, we try to check if b is in the set -> we will get its hash, and, since it collides with a's, the index 'i' will result.
- If at index 'i' we have an entry marked as UNUSED, we will falsely assume 'b' isn't in the set. But if we mark it differently, with 'DUMMY', we know that there was an entry there and new entries might have collided with it and have been moved to another index, so we continue searching until we get to index 'j' and find b. 
</blockquote></details>

Perfect explanation. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pynvm/19#-:-KtVC-DHjIhEFUXNHb1M:bnfp4nl)*

**Comment by catalin-manciu** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[nvm/pmemobj/set.py, line 43 at r4](https://reviewable.io:443/reviews/pmem/pynvm/19#-Ksmo5jPQeEXwMGk2Ifq:-KtXHoXl0tB6wfuJbqGE:b-896fix) ([raw file](https://github.com/pmem/pynvm/blob/8a44499cebd3ce23335a931a83db569aeb417232/nvm/pmemobj/set.py#L43)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

As I can see, mm.malloc() implementation is based on pmemobj_tx_zalloc, so the memory is zeroed. There's no need to fill the table with NULL-oids, unused hashes.

BTW, I think it would be better to have both mm.malloc() and mm.zalloc().
</blockquote></details>

Done.

---

*[nvm/pmemobj/set.py, line 101 at r4](https://reviewable.io:443/reviews/pmem/pynvm/19#-Ksmm5QUoBiUMjOgqWW0:-KtXHsqVUo_1Zw0u8kLO:b-896fix) ([raw file](https://github.com/pmem/pynvm/blob/8a44499cebd3ce23335a931a83db569aeb417232/nvm/pmemobj/set.py#L101)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

Since each reallocation is costly (much more than for DRAM), for PERM_SET_MINSIZE (8) I'd jump to directly to 64.
</blockquote></details>

Done.

---

*[nvm/pmemobj/set.py, line 450 at r4](https://reviewable.io:443/reviews/pmem/pynvm/19#-Ksn9vU7Trqgc8a6CTRE:-KtXHqyN25tMHX-hrWrx:b-896fix) ([raw file](https://github.com/pmem/pynvm/blob/8a44499cebd3ce23335a931a83db569aeb417232/nvm/pmemobj/set.py#L450)):*
<details><summary><i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary><blockquote>

Perfect explanation. Thanks!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/pynvm/19)*

**Comment by bitdancer** [comment]
Having both malloc and zalloc was something I'd intended to go back and fix.  When I started the code everything I was creating needed to be zeroed, so I just used zalloc, but it would indeed be better to have both and I should have named the mm function "correctly" from the start.  Sorry about that.

**Pull request merged**
